### ISSUE TITLE
What is done and what is to be done for the control-dev

### ISSUE THREAD

**Issue by EE-LiuYunhao** [project-herakles/Infantry-RTOS-2019#8] opened 2019-07-07 15:07 UTC
# Tested features

 1. Controlled with RC, mouse and keyboard
 1. Dodging and moving while dodging
 1. Magazine lid
 1. Friction wheel motors

# Remained issues

## Bugs needed solving

- [x]  1. Gimbal rotation is unstable
- [x]  2. Ramp for chassis is a little bit high, not suitable for keyboard controlling
- [x]  3. IMU needs a filter
- [x]  4. Slope for the friction wheel motors
- [x]  4. A higher current limitation for the chassis motors **[HARDWARE ISSUE]**

## Need optimization 

- [x]  1. Chassis power control 
- [x]  2. Parameters for the mouse-key control 
- [x]  3. Auto-aimming

**Comment by BrettDong** [comment] 2019-07-09 16:51
Progress as of the evening of 9 July:

* Basic auto aiming is now available. The robot is able to automatically follow adversarial armor plate given clear and complete vision in sight. There is certain discernible latency, and further optimization (eg. Kalman Filter) is necessary.
* Peculiar gimbal behaviors (eg. unexpected sudden rotation of 90 degrees) caused by flawed 180 degree handling is resolved by reverting the changes.

**Closed as completed** 2019-07-21 15:27 UTC
Labels: bug
